### ISSUE TITLE
Fields should also consider the default values

### ISSUE THREAD

**Issue by rishab951** [smartprix/gqutils#12]
Right now only `args` consider them

Also, default value in args of specific field may not be working.

**Comment by ajeet-smpx** [comment]
Can you give some example of `specifice field` for which default value may not work?

**Comment by rishab951** [comment]
@ajeet-smpx  For example, consider this schema

```
BlogPost = {
	...
	fields: {
		...
		relatedPosts: {
			type: '[BlogPost]',
			args: {
				first: {
					type: 'Int',
					default: 5,
				},
				after: {
					type: 'Int',
					default: 0, // doesn't work in this case
				},
			},
		},
	},
};
```

**Comment by ajeet-smpx** [comment]
@rishab-smpx the example you mentioned is working in my case.

**Comment by ajeet-smpx** [comment]
Found the issue for this example:
https://github.com/smartprix/gqutils/blob/dc9a1fcfb6730c889391df5ea8535c3b653b8f60/src/Schema.js#L455
should be
```js
if (field.default !== undefined)
```

**Comment by ajeet-smpx** [comment]
And, graphql does not provide `defaultValue` for `fields`.
https://graphql.org/graphql-js/type/#graphqlobjecttype

We can wrap resolve function to return default value
```js
field.resolve = _.wrap(field.resolve, async (resolve, ...args) => {
	const value = await resolve(...args);
	return value !== undefined ? value : field.defaultValue;
});
```

**Comment by rohit-gohri** [comment]
> We can wrap resolve function to return default value
> 
> ```js
> field.resolve = _.wrap(field.resolve, async (resolve, ...args) => {
> 	const value = await resolve(...args);
> 	return value !== undefined ? value : field.defaultValue;
> });
> ```

I think we shouldn't do this.
The current scenario is alright, i.e., let graphql server return null and let the client handle defaults.

@rishab-smpx @ajeet-smpx Can we close the issue?

**Comment by rishab951** [comment]
Yes, closing it.
